### ISSUE TITLE
Send Purchase Json to unity instead of just sending sku's . 

### ISSUE THREAD

**Issue by AminSojoudi** [IranUnityGameDevelopers/CafeBazarIabPluginJavaCode#1]
developers need tokens to verify purchases.

**Comment by mhm90** [comment]
Hi,
Based on Android 6 bug:
https://commonsware.com/blog/2015/11/02/psa-android-6p0-theme.nodisplay-regression.html
it is necessary to use `android:theme="@android:style/Theme.Translucent.NoTitleBar"` for `ir.unity3d.cafebazarplugin.GateWay` activity.

**Comment by AminSojoudi** [comment]
Done
