### ISSUE TITLE
Android 6 crach

### ISSUE THREAD

**Issue by mhm90** [IranUnityGameDevelopers/CafeBazarIabPluginJavaCode#3]
Hi,
Based on Android 6 bug:
`https://commonsware.com/blog/2015/11/02/psa-android-6p0-theme.nodisplay-regression.html`
it is necessary to use `android:theme="@android:style/Theme.Translucent.NoTitleBar"` for `ir.unity3d.cafebazarplugin.GateWay` activity.

**Comment by AminSojoudi** [comment]
It's Fixed through your pull request.
